services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./data:/backend/data
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///./data/rental.db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend