"""add location column

Revision ID: 42b5d74b47c4
Revises: 6d9c3ba9004b
Create Date: 2025-07-22 19:36:16.619057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b5d74b47c4'
down_revision: Union[str, Sequence[str], None] = '6d9c3ba9004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('houses', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.alter_column('houses', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('houses', 'image_url')
    op.drop_column('houses', 'location')
    # ### end Alembic commands ###
