"""init

Revision ID: 6d9c3ba9004b
Revises: 
Create Date: 2025-07-22 18:28:25.918723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9c3ba9004b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_index(op.f('ix_houses_title'), 'houses', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_title'), table_name='houses')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
